kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
#################################################
#  Persistent Volume Claim for User database   #
###############################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-user
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M

---
#################################################
#  Persistent Volume Claim for Post database   #
###############################################
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-post
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200M